### ISSUE TITLE
502 error when creating custom domain

### ISSUE THREAD

**Issue by jessding** [hackclub/scrapbook-domains#1]
in Slack I used the command `/scrappy setdomain scrapbook.jessding.com`

my CNAME sets scrapbook.jessding.com to cname.vercel-dns.com, as specified

going to scrapbook.jessding.com gives the same error as going to scrapbook.zachlatta.com

my DNS provider is porkbun, which I don't think is associated with vercel in any way?

**Comment by lachlanjc** [comment]
Hey! Did you use the command `/scrappy setdomain https://scrapbook.jessding.com` by any chance? The HTTPS was in our database, which was breaking it. I removed it, looks like it’s working now: https://scrapbook.jessding.com/

Let me know if you have any other issues!

**Comment by jessding** [comment]
oh ha, i probably did. Thanks for fixing it!
